#cloud-config
hostname: control-plane
fqdn: control-plane.k3s.local
manage_etc_hosts: true

users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: [sudo]
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_public_key}

# Disable the default ubuntu user
system_info:
  default_user:
    name: debian

package_update: true
package_upgrade: false
packages:
  - curl
  - git
  - python3
  - qemu-guest-agent
  - apt-transport-https
  - ca-certificates

# Disable swap (required by Kubernetes)
swap:
  filename: ""
  size: 0

runcmd:
  - swapoff -a
  - sed -i '/ swap / s/^/#/' /etc/fstab
  - systemctl enable --now qemu-guest-agent

power_state:
  mode: reboot
  condition: true
  timeout: 30
